apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-splitwise-deployment
  labels:
    app: simple-splitwise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-splitwise
  template:
    metadata:
      labels:
        app: simple-splitwise
    spec:
      containers:
        - name: splitwise-app-container
          image: simple-splitwise:v5 # <--- MODIFIED: Use image v3
          ports:
            - containerPort: 80
          env:
            - name: APP_GREETING # From previous step
              valueFrom:
                configMapKeyRef:
                  name: simple-splitwise-config
                  key: APP_GREETING
            - name: SPLITWISE_DATA_DIR # <--- NEW ENV VAR
              value: /data # Points to the mount path of our volume
          volumeMounts: # <--- NEW SECTION: Define where to mount volumes inside the container
            - name: splitwise-storage # Must match a volume name defined below
              mountPath:
                /data # Path inside the container where data will be stored
                # This is where SPLITWISE_DATA_DIR points
          # --- NEW: Liveness Probe ---
          livenessProbe:
            httpGet:
              path: /health  # Path to check
              port: 80       # Port on the container to check
            initialDelaySeconds: 15 # Wait 15s after container starts before first probe
            periodSeconds: 20       # Probe every 20s
            timeoutSeconds: 5         # Probe timeout
            failureThreshold: 3       # Consider it failed after 3 consecutive failures

          # --- NEW: Readiness Probe ---
          readinessProbe:
            httpGet:
              path: /health  # Path to check
              port: 80       # Port on the container to check
            initialDelaySeconds: 5  # Wait 5s after container starts before first probe
            periodSeconds: 10       # Probe every 10s
            timeoutSeconds: 5         # Probe timeout
            failureThreshold: 3       # Consider it failed after 3 consecutive failures

      volumes: # <--- NEW SECTION: Define volumes available to this Pod
        - name: splitwise-storage # An arbitrary name for this volume within the Pod spec
          persistentVolumeClaim:
            claimName: simple-splitwise-pvc # The name of the PVC we created
