apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-splitwise-deployment
  labels:
    app: simple-splitwise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-splitwise
  template:
    metadata:
      labels:
        app: simple-splitwise
    spec:
      containers:
      - name: splitwise-app-container
        image: simple-splitwise:v2   # <--- MODIFIED: Use image v2
        # imagePullPolicy: IfNotPresent # Still good to have if image not loaded to Minikube
        ports:
        - containerPort: 80
        env: # <--- NEW SECTION: Define environment variables
          - name: APP_GREETING # Name of the environment variable inside the container
            valueFrom:         # Get the value from a ConfigMap
              configMapKeyRef:
                name: simple-splitwise-config # Name of the ConfigMap we created
                key: APP_GREETING             # The key within the ConfigMap whose value we want
          # You could also set environment variables directly:
          # - name: HARDCODED_ENV_VAR
          #   value: "This is hardcoded"