apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-splitwise-pvc # Name of our PVC
spec:
  accessModes:
    - ReadWriteOnce # Can be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage
  # storageClassName: standard # Optional: Minikube usually has a default 'standard' StorageClass
                               # If you have a specific StorageClass, specify it here.
                               # If omitted and a default exists, that will be used.